# name: Node.js CI

# on:
#   push:
#     branches:
#       - main

#   pull_request:
#     branches:
#       - main

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test
# NOW FOR DOCKER WE WILL USE FROM HERE __________________________________________**********
name: Node.js CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t nodecicd .
        